# Test workflow

name: Test

# Allow run manually
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    # Only run this job for v* tags
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      # Just echo something
      - run: echo "Hello world"
